/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AppMain */

#ifndef _Included_AppMain
#define _Included_AppMain
#ifdef __cplusplus
extern "C" {
#endif
#undef AppMain_WIDTH
#define AppMain_WIDTH 720L
#undef AppMain_HEIGHT
#define AppMain_HEIGHT 480L
/*
 * Class:     AppMain
 * Method:    _init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AppMain__1init(JNIEnv *, jclass);

/*
 * Class:     AppMain
 * Method:    _run
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_AppMain__1run(JNIEnv *, jclass, jobjectArray);

/*
 * Class:     AppMain
 * Method:    _exit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AppMain__1exit(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
