#ifndef INTERRUPTS_H
#define INTERRUPTS_H

#define KEYBOARD_PRESS_INTERRUPT    0x00
#define KEYBOARD_RELEASE_INTERRUPT  0x00

#define MOUSE_MOTION_INTERRUPT      0x00
#define MOUSE_PRESS_INTERRUPT       0x00
#define MOUSE_RELEASE_INTERRUPT     0x00

#endif